repos:
- repo: https://github.com/fluttercommunity/import_sorter
  rev: "aeb26a791ea546506cc8cd2207b320b64a7ed6b5"
  hooks:
    - id: flutter-import-sorter
- repo: https://github.com/dluksza/flutter-analyze-pre-commit
  rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
  hooks:
    - id: flutter-analyze
