import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as Path;

void main() async {
  final Directory cwd = Directory.current;
  final Directory srcDir = Directory(Path.join(cwd.path, 'modules/ffmpeg/dist/mac/license'));
  final List<String> dirList = srcDir.listSync().map((e) => Path.basename(e.path)).toList()..sort();

  Map<String, dynamic> json = {};

  dirList.forEach((libraryName) {
    json[libraryName] = {
      'name': libraryName,
      'version': File(Path.join('${srcDir.path}', libraryName, 'VERSION'))
          .readAsLinesSync()
          .join('')
          .replaceFirst(RegExp(r'^[^\d]+'), ''),
      'license': File(Path.join('${srcDir.path}', libraryName, 'LICENSE'))
          .readAsLinesSync()
          .join('\n')
          .trimRight(),
    };
  });

  final String result = JsonEncoder.withIndent('  ').convert(json);

  File(Path.join('${cwd.path}', 'lib', 'ffmpeg_licenses.dart'))
    ..create()
    ..writeAsStringSync('''
// cSpell:disable
// ignore_for_file: prefer_single_quotes

/// This code was generated by build_scripts/generate_ffmpeg_license_list.dart
final ffmpegLicenses = <String, dynamic>$result;
''');
}
