const TABLE_PADDING_TOP = 5.0;
const TABLE_MINIMUM_HEIGHT = 20.0;
const TABLE_CELL_PADDING_HORIZONTAL = 6.0;
const TABLE_CELL_PADDING_VERTICAL = 0.0;
const TABLE_HEADER_PADDING_HORIZONTAL = 6.0;
const TABLE_HEADER_PADDING_VERTICAL = 3.0;
